version: "2"
services:
  app:
    container_name: bskins-bot
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - "mongodbdata:/data/db"
    ports:
      - "27017:27017"
volumes:
  mongodbdata:
    external: true